version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_course_django
    container_name: "django_${TAG}"
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_course_postgres
    ports:
      - "5432:5432"
    container_name: "postgres_${TAG}"

    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: "mailhog_${TAG}"
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    container_name: "redis_${TAG}"

  celeryworker:
    <<: *django
    image: django_course_celeryworker
    container_name: "celeryworker_${TAG}"
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: django_course_celerybeat
    container_name: "celerybeat_${TAG}"
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: django_course_flower
    container_name: "flower_${TAG}"
    ports:
      - "5555:5555"
    command: /start-flower
